### ISSUE TITLE
Arregla tus errores 

### ISSUE THREAD

**Issue by JulianB0315** [Diego17cp/JavaScript-Road#9]
te recomiendo que cuando hagas algo que no es código correcto no se por ejemplo los comentes por que a veces quiero compilar y no me deja por el error y no si como voy aprender si no puedo compilar 

![Captura de pantalla 2024-08-04 131939](https://github.com/user-attachments/assets/87e6d05a-e084-4f7e-9560-216e6dd36da0)

**Comment by JulianB0315** [comment]
esperando dos días para que acepte mi pull

**Comment by Diego17cp** [comment]
Hola, el código está correcto. Lo que causa conflicto en las clases son las separaciones que hago (---------...), es por eso que te puede lanzar errores, puedes verificarlo compilando sin las separaciones y ya no verás errores:)

**Comment by Diego17cp** [comment]
Hola, el código está correcto. Lo que causa conflicto en las clases son las separaciones que hago (---------...), es por eso que te puede lanzar errores, puedes verificarlo compilando sin las separaciones y ya no verás errores:)
